### ISSUE TITLE
Test script refactoring

### ISSUE THREAD

**Issue by fbornhofen** [LivelyKernel/livelykernel-scripts#1]
Just started branch test_script_refactoring. See also: https://github.com/fbornhofen/life_star.

Idea:
- replace mini_server with life_star
- remove browser-related logic from mini_server and move it to test script 

Status:
- life_star can store and deliver arbitrary data (test results) on a specific route

To do:
- refactoring of run_lively_tests_cli.js; my approach: start from scratch, kind of (inspired by: https://github.com/fbornhofen/lively-ci)

Challenges:
- currently we have at least 4 ways for passing configuration parameters: environment variables, options.js, regular parameters in JS functions, command line arguments
- in the test script, the CLI options parser takes a lot of space. Is that necessary?

Proposed solution:
- test script should have as little CLI args as possible: 
  - "-b" should be there, maybe -s to switch between servers. Everything else should go into config.js
  - paths to test scripts need not be in the environment. Those can go to config.js as well.

Any thoughts?

**Comment by rksm** [comment]
I think as little args as possible is a good thing. However, I like it more to have a general config (env.js) since there is then only one point to change options. For the test options the optional ability to start tests with nodemon (-w, --watch) and run focused tests (-f, --focused) are essential for me.

Also think that the most pressing concern currently is our missing ability to store js / xhtml / js files from inside Lively. Will life_star be able to do that?

**Comment by fbornhofen** [comment]
So I'll probably throw out config.js and move things to env.js.

I'm also happy to announce that the life_star is fully operational! (At least as far as file storage is concerned. (And damn, I've been lurking to write this sentence!))

**Comment by rksm** [comment]
@fbornhofen Cool! :-) How can life_star best be integrated into livelykernel_scripts?

**Comment by fbornhofen** [comment]
My plan is to rewrite the test script so it launches a web browser. That way, mini_server does not have to know about browsers and it works just like life_star.

A while ago I started doing some work in branch test_script_refactoring. Don't remember how far I got, though.

**Comment by rksm** [comment]
Any news on the live_star integration?

**Comment by fbornhofen** [comment]
As of https://github.com/fbornhofen/life_star/commit/7c2cac692e0e2c642e3ff32ad2c79807fdf372d2 we're compatible!

Will create an npm package & integrate it with the scripts in the next couple of days.

**Comment by fbornhofen** [comment]
don't be confused by the date. I did that just now. VM + NTP f***up.

**Comment by fbornhofen** [comment]
Just cleaned up life_star so you can add it as a module to package.json:
 "life_star": "https://github.com/fbornhofen/life_star/tarball/master"
I need to wire it up to the lk script, though.

I guess the idea is to have an additional option to the lk-server script (we have -m already). However, I don't see a clear pattern there of how different servers should have the same interface. Might think of a specification (like, command line arguments host, port, directory, ... in that order.. or a JavaScript function for startup?).

**Comment by rksm** [comment]
Awesome :) Let me know if I can help you somehow with the integration... I really think we should get this going soon...

I already thought that splitting the script commands up in the form of:

``` sh
lk server mini
lk server full
lk ww sync
...
```

might be a good idea in the end. For now just having soem more arguments should work, I guess.
