### ISSUE TITLE
Lifestar error

### ISSUE THREAD

**Issue by rksm** [LivelyKernel/livelykernel-scripts#4]
@fbornhofen I get an error when trying to access http://localhost:9001/blank.xhtml

Any idea what could cause it?

```
➜  core git:(master) lk server -s --lk-dir /Users/robert/Projects/LivelyKernel
Selected life_star
Starting server from /Users/robert/Projects/LivelyKernel. http://localhost:9001
The "sys" module is now called "util". It should have a similar interface.
[2012-04-28 12:20:46.604] [INFO] [default] - GET /blank.xhtml
[2012-04-28 12:20:46.626] [INFO] [default] - GET /core/lively/bootstrap.js

/Users/robert/Dropbox/Projects/lk-scripts/node_modules/life_star/node_modules/jsDAV/lib/DAV/fs/file.js:148
        cbfsgetetag(null, null);
        ^
TypeError: undefined is not a function
    at [object Object].getETag (/Users/robert/Dropbox/Projects/lk-scripts/node_modules/life_star/node_modules/jsDAV/lib/DAV/fs/file.js:148:9)
    at /Users/robert/Dropbox/Projects/lk-scripts/node_modules/life_star/node_modules/jsDAV/lib/DAV/handler.js:1243:70
    at Object.oncomplete (/Users/robert/Dropbox/Projects/lk-scripts/node_modules/life_star/node_modules/jsDAV/lib/DAV/tree/filesystem.js:46:13)
```

**Comment by rksm** [comment]
Wow, I started it multiple times and every time I loaded blank.xhtml. I got a bit farther every time...?! OK, it works now and I can save worlds... yeeeeeeehaaaaa :) Thanks!

Anyway, we should find out what's behind that issue so that it does not occur on user install.

**Comment by fbornhofen** [comment]
Ok so this must have to do with caches again. Will look into it as soon as I have time.

**Comment by rksm** [comment]
OK, thanks. I also hope to report progress re. local workspace support soon.

**Comment by fbornhofen** [comment]
I just did a clean reinstall on my Mac and didn't run into any caching issues. Do yo still have that problem?

**Comment by rksm** [comment]
life_star runs awesomely now :)
